### PR TITLE
A new proposition for pretty messages

### PR DESCRIPTION
**Pull request by SilvrDuck**
I’ve added some markdown formatting to the messages. There’s also a link to explainxkcd.com at the end of each alt comic description.

### CODE REVIEW

**Comment by SilvrDuck** [comment]
@ex0ns : Now the title is in bold, and there is a link to explainxkcd.com. I tried with the alt text in italic, but it was ugly.

It could be good to remove the link preview, but this is a telegram open issue there https://github.com/telegramdesktop/tdesktop/issues/687

Here’s how it looks:
screenshot from 2016-12-17 14-09-01

**Comment by x4080** [comment]
Hi. some website display images in web preview, some website dont, what is the rule to display image in the web preview?

**Comment by mukel** [comment]
You can disable the web preview to get a consistent behavior, check https://github.com/mukel/telegrambot4s/blob/master/src/test/scala/info/mukel/telegrambot4s/examples/LmgtfyBot.scala#L18

**Comment by x4080** [comment]
Yes, I mean when I tried a HTTP link, some won't display the image, is there a rule to make image in the URL appears? I tried Amazon Web Page that won't display the product image

**Comment by mukel** [comment]
The [blog post](https://telegram.org/blog/link-preview) doesn't mention anything, I wrote to their support (not the fastest ever).

**Comment by x4080** [comment]
Ok thanks

**Pull request merged**
